apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uber-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TafariBeckford/DevOps-The-Hard-Way-ArgoCD.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: uber-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true



