apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://helm.elastic.co'
    chart: filebeat
    targetRevision: 7.17.3
    helm:
      valueFiles: 
      - $values/helm-elk/filebeat-values.yaml 
  - repoURL: 'https://github.com/TafariBeckford/DevOps-The-Hard-Way-ArgoCD.git'
    targetRevision: HEAD
    ref: values
   

  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true