apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 45.7.1
    helm:
      valueFiles: 
      - $values/helm-prometheus/values.yaml 
  - repoURL: 'https://github.com/TafariBeckford/DevOps-The-Hard-Way-ArgoCD.git'
    targetRevision: HEAD
    ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-stack

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

    automated:
      prune: true
      selfHeal: true